/**
	@file
	@brief IDL source for CCPDFExcelAddin.dll
*/

/*
 * CC PDF Converter: Windows PDF Printer with Creative Commons license support
 * Copyright (C) 2007 Guy Hachlili <hguy@cogniview.com>, Cogniview LTD.
 * 
 * This file is part of CC PDF Converter.
 * 
 * CC PDF Converter is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CC PDF Converter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. * 
 */

// This file will be processed by the MIDL tool to
// produce the type library (CCPDFExcelAddin.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(1FD93D67-9174-4BD0-A7D2-9BA241870079),
		dual,
		helpstring("ICCPDFExcelAddinObj Interface"),
		pointer_default(unique)
	]
	interface ICCPDFExcelAddinObj : IDispatch
	{
	};

[
	uuid(0BA12602-CB78-430F-AA09-77A5F1CF29C0),
	version(1.0),
	helpstring("CCPDFExcelAddin 1.0 Type Library")
]
library CCPDFEXCELADDINLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(7A13F11B-2986-4C4C-82B4-D5FEA66BB36F),
		helpstring("CCPDFExcelAddinObj Class")
	]
	coclass CCPDFExcelAddinObj
	{
		[default] interface ICCPDFExcelAddinObj;
	};
};
